version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: conf
    versions:
    - 10.0.0
    - 9.0.0
    - 9.0.1
    - 9.0.2
  - dependency-name: mem
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: chalk
    versions:
    - 4.1.0
